# Generated by Django 4.0.6 on 2022-07-21 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('talk', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='talk',
            old_name='description',
            new_name='abstract',
        ),
        migrations.RemoveField(
            model_name='talk',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='talk',
            name='start_time',
        ),
    ]
