# Generated by Django 4.0.6 on 2022-07-21 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speaker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='speaker',
            name='bio',
            field=models.TextField(default='Talk bio'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='speaker',
            name='company',
            field=models.CharField(default='Zillatide', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='speaker',
            name='email',
            field=models.EmailField(default='speaker@email.com', max_length=255),
            preserve_default=False,
        ),
    ]
