# Generated by Django 4.0.6 on 2022-07-21 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('speaker', '0002_speaker_bio_speaker_company_speaker_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='speaker',
            name='company',
        ),
        migrations.RemoveField(
            model_name='speaker',
            name='email',
        ),
        migrations.RemoveField(
            model_name='speaker',
            name='name',
        ),
    ]
