# Generated by Django 4.0.6 on 2022-07-21 02:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('speaker', '0003_remove_speaker_company_remove_speaker_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='speaker',
            name='user',
            field=models.OneToOneField(default=2, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
